spring:
  datasource:
    url: jdbc:h2:mem:atm
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
